import "frida-il2cpp-bridge";

import { AssemblyHelper } from "./core/assembly-helper";
import { ModuleManager } from "./core/module-manager";
import { I18n } from "./i18n/i18n";
import { Logger } from "./logger/logger";
import { initSettingsUI } from "./ui/settings";
import { getSonolusVersion } from "./utils/version";

function init(): void {
    Logger.info("Script loaded!");

    Il2Cpp.perform(() => {
        Logger.info("Il2cpp loaded!");
        AssemblyHelper.init();

        // Hash generated by frida-il2cpp-bridge
        Logger.infoGreen(`SonolusReverse. Version Hash: ${Il2Cpp.application.version} | Game Version: ${getSonolusVersion()}`);

        I18n.init(); // Read locale from game, should init after Assemblies
        ModuleManager.initAll();

        // Init UI
        initSettingsUI();
    }).catch(error => Logger.error(`Failed to init script: ${error}`));
}

init();
