import "frida-il2cpp-bridge";

import { AssemblyHelper } from "./core/assembly-helper";
import { ModuleManager } from "./core/module-manager";
import { Config } from "./data/config";
import { ModPreferences } from "./data/mod-preferences";
import { ThemeLoader } from "./data/theme-loader";
import { I18n } from "./i18n/i18n";
import { Logger } from "./logger/logger";
import { initSettingsUI } from "./ui/settings";
import { ConfigRef } from "./utils/config-ref";
import { SonolusUtils } from "./utils/version";

function logBanner(): void {
    const { VERSION, ENV, COMMIT, FOR_GAME_VERSION } = ModPreferences;
    // Hash generated by frida-il2cpp-bridge
    const hash = Il2Cpp.application.version;
    const gameVer = SonolusUtils.getSonolusVersion();
    Logger.infoGreen(`SonolusReverse v${VERSION} - #${COMMIT} (${ENV}). Version Hash: ${hash} | Game Version: ${gameVer}`);

    if (FOR_GAME_VERSION !== gameVer) {
        Logger.warn(`Sonolus version ${gameVer} isn't supported by SonolusReverse. Script will still load, but things may break`);
    }
}

function init(): void {
    Logger.info("Script loaded!");

    Il2Cpp.perform(() => {
        /// #if DEV
        Il2Cpp.installExceptionListener("all");
        /// #endif

        Logger.info("Il2cpp loaded!");
        AssemblyHelper.init();

        logBanner();

        // Init Config & Themes
        Config.load();
        ConfigRef.init();
        ThemeLoader.load();

        I18n.init(); // Read locale from game, should init after Assemblies
        ModuleManager.initAll();

        // Init UI
        initSettingsUI();
    }).catch(error => Logger.error(`Failed to initialize script: ${error}`));
}

init();
