name: Build Sonolus APK with SonolusReverse Script

on:
  push:
    tags:
      - "v*"

jobs:
  build: 
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with: 
          node-version: latest
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Build Script
        run: npm run build:nobump

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK 
        uses: android-actions/setup-android@v4
        with:
          packages: 'build-tools;34.0.0'

      - name: Link Android SDK Build Tools
        run: |
          TOOLS_DIR="$ANDROID_HOME/build-tools/34.0.0"
          echo "Linking tools from: $TOOLS_DIR"
          
          sudo ln -sf "$TOOLS_DIR/zipalign" /usr/local/bin/zipalign
          sudo ln -sf "$TOOLS_DIR/apksigner" /usr/local/bin/apksigner
        
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
        
      - name: Install Python Build dependencies  
        run: pip install -r requirements_build.txt

      - name: Extract Sonolus Version from Source
        run: | 
          VERSION=$(sed -n 's/.*FOR_GAME_VERSION = "\([^"]*\)".*/\1/p' src/mod/data/ModPreferences.ts)
          echo "Extracted Sonolus Version: $VERSION"
          echo "SONOLUS_VERSION=$VERSION" >> $GITHUB_ENV

      # Download and Patch APK
      - name: Download Sonolus APK
        run: wget https://download.sonolus.com/Sonolus_${{ env.SONOLUS_VERSION }}.apk

      - name: Patch APK
        run: fgi -i Sonolus_${{ env.SONOLUS_VERSION }}.apk -t script -l dist/agent.js -o dist/SonolusReverse_${{ env.SONOLUS_VERSION }}.apk

      # Upload
      - name: Upload Patched APK
        uses: softprops/action-gh-release@v3
        with: 
          tag_name: ${{ github.ref_name }}
          files: "dist/SonolusReverse_${{ env.SONOLUS_VERSION }}.apk"
          body_path: ".github/release-notes.md"